import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

function run(cmd, args) {
  return execFileSync(cmd, args, { encoding: 'utf8' }).trim();
}

function tryRun(cmd, args) {
  try {
    return run(cmd, args);
  } catch {
    return null;
  }
}

function formatUtcTimestamp(date = new Date()) {
  return date.toISOString().replace(/\.\d{3}Z$/, 'Z');
}

function sanitizePath(filePath, repoRoot) {
  if (typeof filePath !== 'string') return String(filePath ?? '');
  const normalizedRoot = path.resolve(repoRoot);
  const resolved = path.resolve(filePath);
  if (resolved === normalizedRoot) return '.';
  if (resolved.startsWith(`${normalizedRoot}${path.sep}`)) return path.relative(normalizedRoot, resolved);
  return filePath;
}

function summarizeFindings(findings) {
  const summary = { total: 0, byDetector: {} };
  for (const [detector, issues] of Object.entries(findings)) {
    const count = Array.isArray(issues) ? issues.length : 0;
    summary.total += count;
    summary.byDetector[detector] = count;
  }
  return summary;
}

function renderMarkdownReport(args) {
  const lines = [];
  lines.push('# Snapper Report');
  lines.push('');
  lines.push(`Generated: \`${args.generatedAt}\``);
  if (args.commitSha) lines.push(`Commit: \`${args.commitSha}\``);
  if (args.snapperVersion) lines.push(`Snapper: \`${args.snapperVersion}\``);
  if (args.snapPackageName && args.snapVersion) {
    lines.push(`Target: \`${args.snapPackageName}@${args.snapVersion}\` (\`${args.snapPath}\`)`);
  } else {
    lines.push(`Target: \`${args.snapPath}\``);
  }
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Total issues: **${args.summary.total}**`);
  for (const [detector, count] of Object.entries(args.summary.byDetector).sort((a, b) => a[0].localeCompare(b[0]))) {
    lines.push(`- ${detector}: **${count}**`);
  }

  lines.push('');
  lines.push('## Details');
  lines.push('');
  if (args.summary.total === 0) {
    lines.push('- No findings.');
    lines.push('');
  }
  for (const [detector, issues] of Object.entries(args.findings).sort((a, b) => a[0].localeCompare(b[0]))) {
    if (!Array.isArray(issues) || issues.length === 0) continue;
    lines.push(`### ${detector}`);
    lines.push('');
    lines.push('| Risk | File | Line | Description |');
    lines.push('| ---: | ---- | ---: | ----------- |');

    const sorted = issues
      .slice()
      .sort((a, b) => {
        const aPath = a?.position?.filePath ?? '';
        const bPath = b?.position?.filePath ?? '';
        const p = String(aPath).localeCompare(String(bPath));
        if (p !== 0) return p;
        const aLine = Number(a?.position?.lineNum ?? 0);
        const bLine = Number(b?.position?.lineNum ?? 0);
        return aLine - bLine;
      })
      .map((issue) => ({
        risk: issue?.riskRating ?? '',
        file: issue?.position?.filePath ?? '',
        line: issue?.position?.lineNum ?? '',
        description: issue?.description ?? '',
      }));

    for (const issue of sorted) {
      const file = sanitizePath(issue.file, args.repoRoot);
      const line = issue.line ?? '';
      const risk = issue.risk ?? '';
      const desc = String(issue.description).replace(/\|/g, '\\|');
      lines.push(`| ${risk} | \`${file}\` | ${line} | ${desc} |`);
    }
    lines.push('');
  }

  lines.push('## How to regenerate');
  lines.push('');
  lines.push('```bash');
  lines.push('pnpm snapper:report');
  lines.push('```');
  lines.push('');
  lines.push(
    'Note: Snapper currently outputs JSON (and optional HTML) reports. This Markdown file is generated by converting Snapper JSON output.',
  );
  lines.push('');

  return `${lines.join('\n')}\n`;
}

const repoRoot = process.cwd();
const snapPath = path.join(repoRoot, 'snaps', 'ddrp-snap');
const reportPath = path.join(repoRoot, 'SNAPPER_REPORT.md');

const commitSha = tryRun('git', ['rev-parse', 'HEAD']);
const snapperVersion = tryRun('npx', ['--yes', '@sayfer_io/snapper', '--version']);
let snapPackageName = null;
let snapVersion = null;
try {
  const snapPkg = JSON.parse(fs.readFileSync(path.join(snapPath, 'package.json'), 'utf8'));
  snapPackageName = snapPkg?.name ?? null;
  snapVersion = snapPkg?.version ?? null;
} catch {
  // ignore
}

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'snapper-'));
try {
  const tmpJson = path.join(tmpDir, 'snapper.json');
  execFileSync(
    'npx',
    ['--yes', '@sayfer_io/snapper', '--path', snapPath, '--output', tmpJson],
    { stdio: 'inherit' },
  );

  const findings = fs.existsSync(tmpJson) ? JSON.parse(fs.readFileSync(tmpJson, 'utf8')) : {};
  const summary = summarizeFindings(findings);

  const md = renderMarkdownReport({
    repoRoot,
    generatedAt: formatUtcTimestamp(),
    commitSha,
    snapperVersion,
    snapPackageName,
    snapVersion,
    snapPath: path.relative(repoRoot, snapPath),
    summary,
    findings,
  });

  fs.writeFileSync(reportPath, md);
  console.log(`Wrote ${path.relative(repoRoot, reportPath)}`);
} finally {
  fs.rmSync(tmpDir, { recursive: true, force: true });
}
